---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  build-package:
    strategy:
      matrix:
        package:
          - terraform
          - terraform-provider-aws
    runs-on: ubuntu-latest
    name: Build ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: nix-terraform
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store nix-terraform &

      - name: Build
        run: nix build .#${{ matrix.package }}
