---
name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22

      - uses: cachix/cachix-action@v12
        with:
          name: nix-terraform
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store nix-terraform &

      - name: Check main flake
        run: nix flake check

      - name: Check tests
        run: nix flake check ./dev
