---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      checks: ${{ steps.checks.outputs.checks }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          diagnostic-endpoint: ''

      - name: Find checks
        id: checks
        run: |
          nix eval --json --apply builtins.attrNames ./dev#checks.x86_64-linux | sed 's|^|checks=|' >>$GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          diagnostic-endpoint: ''

      - uses: cachix/cachix-action@v14
        with:
          name: nix-terraform
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store nix-terraform &

      - name: Run check
        run: nix flake check

  dev-check:
    name: Check
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        check: ${{ fromJSON(needs.prepare.outputs.checks) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
        with:
          diagnostic-endpoint: ''

      - uses: cachix/cachix-action@v14
        with:
          name: nix-terraform
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store nix-terraform &

      - name: Run check
        run: |
          nix build ./dev#checks.x86_64-linux.${{ matrix.check }}
