---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          diagnostic-endpoint: ''

      - uses: cachix/cachix-action@v12
        with:
          name: nix-terraform
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store nix-terraform &

      - name: Check
        run: nix flake check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          diagnostic-endpoint: ''

      - uses: cachix/cachix-action@v12
        with:
          name: nix-terraform
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Enable incremental cache upload
        run: cachix watch-store nix-terraform &

      - name: Check
        run: nix flake check ./dev
