---
name: Update flake.lock

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  flake-lock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18

      - uses: tibdex/github-app-token@v1.8.0
        id: generate-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          token: ${{ steps.generate-app-token.outputs.token }}
          branch: update-flake-lock
          pr-labels: |
            chore
            flake
            automation

  tests-flake-lock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18

      - uses: tibdex/github-app-token@v1.8.0
        id: generate-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update tests/flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          path-to-flake-dir: tests/
          token: ${{ steps.generate-app-token.outputs.token }}
          branch: update-tests-flake-lock
          pr-title: "Update tests/flake.lock"
          pr-labels: |
            chore
            flake
            automation
